version: "3.7"

services:
    database:
        image: postgres
        container_name: database_ignite
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=rental-x
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: rental-x
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - database_ignite
        depends_on: 
            - database_ignite

volumes:
    pgdata:
        driver: local